[tool.ruff]
# Target Python 3.8+
target-version = "py38"

# Line length to match Black's default
line-length = 88

# Exclude directories
exclude = [
    ".venv",
    "venv",
    "__pycache__",
    ".git",
    "output",
]

[tool.ruff.lint]
# Enable pycodestyle (E), pyflakes (F), and isort (I) rules
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "C4",   # flake8-comprehensions
]

# Ignore specific rules
ignore = [
    "E501",  # line too long (handled by formatter)
    "E731",  # lambda assignment
]

[tool.ruff.lint.per-file-ignores]
# Allow unused imports in __init__.py
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
# Use a single line for imports
combine-as-imports = true